### PR TITLE
Correct composer's reference to fyneworks/jquery-star-ratin

### PR DESCRIPTION
**Pull request by lucasaba**

### CODE REVIEW

**Comment by lucasaba** [comment]
Well, that's not clear for me....maybe I've made a mistake.
But in 6cebcc9386d934930aaa74245fba8de5b7db88c9 you've deleted the remote repository and use composer.json, then in 0a71cd7039e76552133be97811608d01e400592c you put it back...

**Comment by nurikabe** [comment]
I'm pretty sure https://github.com/fyneworks/star-rating is the correct URL

**Comment by lucasaba** [comment]
Yes, absolutely. That's why I'm confused....maybe I'm having some sort of problem with composer. So, when I update, it says that it can't find fyneworks/star-rating master.
I didn't note the "repositories" section so I've checked packagist and I saw that there's a https://packagist.org/packages/fyneworks/jquery-star-rating package. 
I've noted just now that the mainteiner is not fyneworks but bloody_hell...so maybe we can close this issue....my mistake!
Still I've to understand why composer is not downloading the package....

**Comment by nurikabe** [comment]
Try explicitly requiring `fyneworks/star-rating`.  For example:

        "fyneworks/star-rating": "dev-master",
        "nurikabe/star-rating-bundle": "2.0.0",

**Comment by lucasaba** [comment]
It works! :+1: 

Thanks and sorry.....

**Pull request closed without merging**
